/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#a0d0c2",
        "surface-container-highest": "#e1e3e2",
        "primary-fixed": "#bcedde",
        "on-primary-fixed-variant": "#204e44",
        "tertiary": "#36403e",
        "primary-container": "#2f5d52",
        "on-tertiary-fixed": "#141d1c",
        "secondary-container": "#b7ede2",
        "secondary": "#34675e",
        "surface-bright": "#f8faf9",
        "inverse-surface": "#2e3131",
        "on-error": "#ffffff",
        "surface": "#f8faf9",
        "on-primary-container": "#a3d4c6",
        "surface-variant": "#e1e3e2",
        "on-tertiary-container": "#c2ccc9",
        "on-secondary-fixed": "#00201c",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dbe5e2",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceeed",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#9cd1c6",
        "outline-variant": "#c0c8c4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3f4947",
        "tertiary-fixed-dim": "#bfc9c6",
        "secondary-fixed": "#b7ede2",
        "on-secondary-fixed-variant": "#194f47",
        "on-secondary-container": "#3a6d64",
        "error-container": "#ffdad6",
        "tertiary-container": "#4d5755",
        "on-primary-fixed": "#00201a",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1c",
        "primary-fixed-dim": "#a0d0c2",
        "surface-tint": "#39675b",
        "error": "#ba1a1a",
        "background": "#f8faf9",
        "inverse-on-surface": "#eff1f0",
        "surface-dim": "#d8dad9",
        "on-background": "#191c1c",
        "primary": "#15453b",
        "surface-container-high": "#e6e9e8",
        "surface-container-low": "#f2f4f3",
        "outline": "#707976",
        "on-surface-variant": "#404846"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
